generated
reduceTable
^#(
	#(14 0 #reduceActionForChannels1: 507905 false ) 
	#(13 4 #reduceActionForToplevel1: 385025 false ) 
	#(14 2 #reduceActionForChannels2: 507906 false ) 
	#(19 1 #reduceActionForSymbol1: 1035265 false ) 
	#(20 1 #reduceActionForString1: 1091585 false ) 
	#(15 6 #reduceActionForChannel1: 609281 false ) 
	#(16 5 #reduceActionForName1: 779265 false ) 
	#(17 4 #reduceActionForUrl1: 869377 false ) 
	#(18 4 #reduceActionForUrl1: 949249 false )
	).